server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/flowmanager

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG

gateway:
  internal-secret: ${GATEWAY_SECRET}