spring:
  application:
    name: nomenclator
  profiles:
    default: dev

server:
  port: 8082

keycloak:
  admin:
    url: http://localhost:8080
    realm: flowmanager
    client-id: flowmanager-client
    client-secret: ${KEYCLOAK_CLIENT_SECRET}

gateway:
  internal-secret: ${GATEWAY_SECRET}

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    flowmanager.nomenclator: DEBUG
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  file:
    path: logs