spring:
  application:
    name: nomenclator
  profiles:
    default: dev

server:
  port: 8082

keycloak:
  admin:
    url: http://localhost:8080
    realm: flowmanager
    client-id: flowmanager-client
    client-secret: ${KEYCLOAK_CLIENT_SECRET}

gateway:
  internal-secret: ${GATEWAY_SECRET}

logging:
  config: classpath:logback-spring.xml

management:
  tracing:
    sampling:
      probability: 0.1
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: nomenclator