spring.application.name=nomenclator
server.port=8082
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.show-sql=false
gateway.internal-secret=${GATEWAY_SECRET}
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/flowmanager