global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nomenclator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['flowmanager-nomenclator.internal:8082']

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['flowmanager-api-gateway.internal:8081']
